### ISSUE TITLE
update to opentelemetry v1.9.1 & v0.28b1

### ISSUE THREAD

**Issue by gam-phon** [uptrace/uptrace-python#93]

**Comment by vmihailenco** [comment]
@gam-phon the update is almost ready. Turns out you can't use metrics with otel-python yet - see https://github.com/open-telemetry/opentelemetry-python/issues/2378

**Comment by vmihailenco** [comment]
Just released v1.9.1 . Metrics support will be released once opentelemetry-python is ready.

**Comment by gam-phon** [comment]
Thank you so much

**Comment by vmihailenco** [comment]
@gam-phon metrics should be working in v1.10.0. See https://github.com/uptrace/uptrace-python/tree/master/example/metrics as an example.
